### ISSUE TITLE
Pointer to Documentation? (xAPI adapter)

### ISSUE THREAD

**Issue by FlorianTolk** [cassproject/devs.cassproject.org#1]
I've been trying to test the xAPI adapter i.e. to retrieve xAPI statements and turn those into assertions. I can't find the documentation on using the xAPI adapters that are found on the git.

Is there documentation anywhere that will explain how to use this adapter to have CASS automatically pull from an LRS (I am using learning locker, in case that makes any difference), and then use these statements to make assertions that quote the pulled statements as evidence?

Thanks in advance!

**Comment by Lomilar** [comment]
http://devs.cassproject.org/index.html?doc=1DZlrMrPd8Me2BsYHB0vUovtocWUMaj_VvKQD2_Ibb70#h.r5xxv2r1prwz
