### ISSUE TITLE
API Documentation missing for EcRepository.multiget

### ISSUE THREAD

**Issue by whistlinjoe** [cassproject/devs.cassproject.org#5]
No API documentation segment exists for EcRepository.multiget (should be: http://cassproject.github.io/CASS/docs/classes/EcRepository.html#method_multiget)

EcRepository.get exists twice (http://cassproject.github.io/CASS/docs/classes/EcRepository.html#method_get)

**Comment by Lomilar** [comment]
To correct, See documentation style in eduworks/ec/src/main/.../EcRepository.java

**Comment by whistlinjoe** [comment]
Complete
